import Card from "#/client/elements/card";
import NextLink from "#/client/elements/link";

const Page = () => {
  return (
    <>
      <Card
        $color="primary"
        $accordion
      >
        <>Elements</>
        <ul>
          <li>
            Container
            <ul>
              <li>
                <NextLink>
                  Navigation
                </NextLink>
              </li>
              <li>
                <NextLink>
                  Card
                </NextLink>
              </li>
              <li>
                <NextLink>
                  GroupBox
                </NextLink>
              </li>
              <li>
                <NextLink>
                  TabContainer
                </NextLink>
              </li>
              <li>
                <NextLink>
                  SlideContainer
                </NextLink>
              </li>
              <li>
                <NextLink>
                  SplitContainer
                </NextLink>
              </li>
            </ul>
          </li>
          <li>
            <NextLink>
              Form
            </NextLink>
            <ul>
              <li>
                <NextLink>
                  CheckBox
                </NextLink>
              </li>
              <li>
                <NextLink>
                  CheckList
                </NextLink>
              </li>
              <li>
                <NextLink>
                  ToggleBox
                </NextLink>
              </li>
              <li>
                <NextLink>
                  RadioButtons
                </NextLink>
              </li>
              <li>
                <NextLink>
                  TextBox
                </NextLink>
              </li>
              <li>
                <NextLink>
                  PasswordBox
                </NextLink>
              </li>
              <li>
                <NextLink>
                  CreditCardBox
                </NextLink>
              </li>
              <li>
                <NextLink>
                  TextArea
                </NextLink>
              </li>
              <li>
                <NextLink>
                  NumberBox
                </NextLink>
              </li>
              <li>
                <NextLink>
                  Slider
                </NextLink>
              </li>
              <li>
                <NextLink>
                  SelectBox
                </NextLink>
              </li>
              <li>
                <NextLink>
                  DatePicker
                </NextLink>
              </li>
              <li>
                <NextLink>
                  DateBox
                </NextLink>
              </li>
              <li>
                <NextLink>
                  DateRangeBox
                </NextLink>
              </li>
              <li>
                <NextLink>
                  TimePicker
                </NextLink>
              </li>
              <li>
                <NextLink>
                  TimeBox
                </NextLink>
              </li>
              <li>
                <NextLink>
                  FileButton
                </NextLink>
              </li>
              <li>
                <NextLink>
                  FileDrop
                </NextLink>
              </li>
              <li>
                <NextLink>
                  ElectronicSignature
                </NextLink>
              </li>
              <li>
                <NextLink>
                  Hidden
                </NextLink>
              </li>
            </ul>
          </li>
          <li>
            Control
            <ul>
              <li>
                <NextLink>
                  Button
                </NextLink>
              </li>
              <li>
                <NextLink>
                  LinkButton
                </NextLink>
              </li>
              <li>
                <NextLink>
                  NextLink
                </NextLink>
              </li>
              <li>
                <NextLink>
                  Menu
                </NextLink>
              </li>
              <li>
                <NextLink>
                  Popup
                </NextLink>
              </li>
            </ul>
          </li>
          <li>
            View
            <ul>
              <li>
                <NextLink>
                  text
                </NextLink>
              </li>
              <li>
                <NextLink>
                  Label
                </NextLink>
              </li>
              <li>
                <NextLink>
                  Badge
                </NextLink>
              </li>
              <li>
                <NextLink>
                  Tooltip
                </NextLink>
              </li>
              <li>
                <NextLink>
                  DataTable
                </NextLink>
              </li>
              <li>
                <NextLink>
                  DataList
                </NextLink>
              </li>
              <li>
                <NextLink>
                  StructView
                </NextLink>
              </li>
            </ul>
          </li>
          <li>
            State
            <ul>
              <li>
                <NextLink>
                  Loading
                </NextLink>
              </li>
              <li>
                <NextLink>
                  Stepper
                </NextLink>
              </li>
            </ul>
          </li>
          <li>
            Others
            <ul>
              <li>
                <NextLink>
                  Divider
                </NextLink>
              </li>
              <li>
                <NextLink>
                  MessageBox
                </NextLink>
              </li>
            </ul>
          </li>
        </ul>
      </Card>
    </>
  );
};

export default Page;