type Color = "base"
  | "border"
  | "shadow"
  | "pure"
  | "dull"
  | "main"
  | "main-light"
  | "main-dark"
  | "sub"
  | "sub-light"
  | "sub-dark"
  | "primary"
  | "secondary"
  | "tertiary"
  | "warning"
  | "danger"
  | "cool"
  | "pretty"
  ;