type Color = "base"
  | "pure"
  | "dull"
  | "border"
  | "shadow"
  | "mask"
  | "input"
  | "error"
  | "nav"
  | "main"
  | "main-light"
  | "main-dark"
  | "sub"
  | "sub-light"
  | "sub-dark"
  | "primary"
  | "secondary"
  | "tertiary"
  | "warning"
  | "danger"
  | "cool"
  | "pretty"
  ;

type Size = "xs" | "s" | "m" | "l" | "xl";