version: '3'
services:
  node:
    container_name: 'node_dev'
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    image: 'node_dev_image'
    tty: true
    volumes:
      - '../:/workspace'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${PORT:-3000}:3000'
    command:
      /bin/bash -c "npm i && npm run dev"
