version: '3'
services:
  node:
    container_name: 'node_dev'
    build:
      context: '../'
      dockerfile: '.devcontainer/docker/node/Dockerfile'
    image: 'node_dev_image'
    tty: true
    volumes:
      - '../:/workspace'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - 'WATCHPACK_POLLING=true'
      - 'LOCALHOST=${LOCALHOST:-host.docker.internal}'
      - 'NEXT_PORT=${NEXT_PORT:-3000}'
      - 'NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}'
      - 'NEXTAUTH_URL_INTERNAL=${NEXTAUTH_URL_INTERNAL:-http://localhost:3000}'
      - 'NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-secret}'
    ports:
      - '${NEXT_PORT:-3000}:${NEXT_PORT:-3000}'
    command:
      /bin/bash -c "npm i && npm run dev"
