version: '3'
services:
  node:
    container_name: node_dev
    build:
      context: .
      dockerfile: Dockerfile
    image: node_dev_image
    tty: true
    volumes:
      - ../:/workspace