version: '3'
services:
  node:
    container_name: 'node-app-template'
    build:
      context: '../'
      dockerfile: '.prodcontainer/docker/node/Dockerfile'
    image: 'node-app-template'
    tty: true
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - 'NEXT_PORT=${NEXT_PORT:-3000}'
      - 'NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}'
      - 'NEXTAUTH_URL_INTERNAL=${NEXTAUTH_URL_INTERNAL:-http://localhost:3000}'
      - 'NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-secret}'
    ports:
      - '${NEXT_PORT:-3000}:${NEXT_PORT:-3000}'
