version: '3'
services:
  node:
    container_name: 'node-app-template'
    env_file:
      - path: '../.env'
        required: true
      - path: '../.env.local'
        required: false
    build:
      context: '../'
      dockerfile: '.prodcontainer/docker/node/Dockerfile'
    image: 'node-app-template'
    tty: true
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${NEXT_PORT:-3000}:${NEXT_PORT:-3000}'
